### PR TITLE
[WIP] Quality Assurance Pipeline

### PR DESCRIPTION
**Pull request by acchiao**
[Rendered](https://stjudecloud.github.io/rfcs/branches/achiao/quality-assurance-pipeline/0000-quality-assurance-pipeline.html)

### CODE REVIEW

**Comment by adthrasher** [comment]
As I think about this, I want to make sure I'm clear on the purpose of the QA. In my mind, we have two purposes. First, we want to make sure that what we post and deliver to users is a complete, accurate replication of what we originally generated, e.g. the remapped bam has the same data as the original bam from the cluster pipelines. Second, we want to demonstrate to our users that SJC data is consistent and of high quality suitable for analysis. 

To me, the motivation section reads as though we're addressing both of those needs in the RFC, but the described process seems more oriented toward the second. As a public RFC, it seems like focussing on the second purpose would be of more interest to the community. However, we have been using these QA results internally to address the first purpose and we should have a conversation about what automated metrics are applicable.

**Comment by adthrasher** [comment]
An additional suggestion, add an automated check to ensure that the sequence dictionary in the bam header matches an expected sequence dictionary.

**Comment by adthrasher** [comment]
Here's a dashboard for fastQC output: https://github.com/pnnl/fqc.

**Comment by claymcleod** [comment]
I'm testing out getting better CI workflows, so I've renamed the branch and opened another PR here: https://github.com/stjudecloud/rfcs/pull/13

**Pull request closed without merging**
